version: '2'
services:
    domotikweb-app:
        image: domotikweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://domotikweb-mysql:3306/domotikweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    domotikweb-mysql:
        extends:
            file: mysql.yml
            service: domotikweb-mysql
